name: flutter_widget_app
description: A collection of reusable Flutter widgets with press animations, shimmer effects, and customizable buttons.
version: 1.0.3

homepage: https://github.com/abhaybeetnoz-cyber/flutter_widget_app
repository: https://github.com/abhaybeetnoz-cyber/flutter_widget_app
issue_tracker: https://github.com/abhaybeetnoz-cyber/flutter_widget_app/issues

topics:
  - flutter
  - widgets
  - animations
  - shimmer
  - scale

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^2.0.0
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
